# Uncomment the next line to define a global platform for your project
 platform :ios, '12.1'

target 'GBMChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GBMChallenge
  pod 'SwiftLint'
  pod 'lottie-ios'
  pod 'SwiftChart'
  pod 'Charts'
  target 'GBMChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GBMChallengeUITests' do
    # Pods for testing
  end

end
